import './globals.css'
import type { Metadata } from 'next'
import { SessionProvider } from "next-auth/react"
import { Fira_Sans } from 'next/font/google'

const fira = Fira_Sans({ subsets: ['latin'], weight: "500" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
        <head>
          <link rel="manifest" href="/manifest.json" />
        </head>
        <SessionProvider session={session}>
          <body className={fira.className}>{children}</body>
        </SessionProvider>
    </html>
  )
}
